### PR TITLE
Hotfix iteration

### PR DESCRIPTION
**Pull request by JacobJoseph-gu**

### CODE REVIEW

**Comment by RudoRoemer** [comment]
As before, have you checked that the output in the samples remains unchanged in terms of numbers/images?

**Comment by JacobJoseph-gu** [comment]
I have made some final tweaks. Yes, the final values matches and I have checked that one of the final binary images match.

**Comment by rbeanland** [comment]
By the way I have found that felixrefine crashes when running in simulation only mode (option S), does this happen for your branch too?

**Comment by JacobJoseph-gu** [comment]
I am not familiar with simulation only mode, but I will look into that and get that working. Is it fine to leave simplex not working?

**Comment by rbeanland** [comment]
Hi Jacob,
It is fine to leave simplex broken, if it is (I haven't tried it in a while). Although I suspect it would not be hard to fix.

Richard

On 4 Sep 2017, at 16:26, JacobJoseph-gu <notifications@github.com<mailto:notifications@github.com>> wrote:


I am not familiar with simulation only mode, but I will look into that and get that working. Is it fine to leave simplex not working?

**Comment by JacobJoseph-gu** [comment]
After looking at the simulation only code it looks like simulation-only hasn't worked for a long time? Have you got it working recently?

I set IRefineFLAG = S
I checked this with an old commit 920316ecd698a3ee25539949e98f214bb9368a64, before I started working on the code.

Soon I will spend some time trying to make both of these work and see how it goes.

**Comment by JacobJoseph-gu** [comment]
Are we okay with this pull request? I have another large pull request afterwards to merge which includes the dm3 reader, the new experimental images folders and workflow, tidied message subroutine and some tidied comments throughout felix.

I will then look into the tinis compiler error and fixing simulation-only and simplex.

**Pull request merged**
