### PR TITLE
Vector refinement method installed, unknown bug preventing iteration

### PR DESCRIPTION
**Pull request by kidwhizz**

### CODE REVIEW

**Comment by RudoRoemer** [comment]
aquarius src>make
mpif90 -fbounds-check -fno-range-check -fimplicit-none -fcray-pointer  -DF90 -c gmodules.f90 -I/warwick/mathlib/gnu/x86_64/  -llapack -lblas -lfftw3
mpif90 -fbounds-check -fno-range-check -fimplicit-none -fcray-pointer  -DF90 -c smodules.f90 -I/warwick/mathlib/gnu/x86_64/  -llapack -lblas -lfftw3
smodules.f90:280.31:

        IVariableID,IFelixCount,IPreviousPrintedIteration
                               1
Error: Symbol 'ifelixcount' at (1) already has basic type of INTEGER
make: *** [smodules.o] Error 1

**Comment by RudoRoemer** [comment]
Or maybe this is Alex' mistake?

**Comment by AJMHubert** [comment]
I added a new Variable (IMessagecounter) at the bottom of IPara, where Keith also added some new variables, so we had a conflict. I think what has happened is that the Variables IFelixCount & IPreviousPrintedIteration have been copied. I have Quickly fixed (locally) and tested. seems to now be a problem with Subroutine ConvertVectorMovementsIntoAtomicCoordinates (Array mismatch) in felixfunction - but that is in Keith's domain

**Comment by RudoRoemer** [comment]
Well, what I am interested in is code that works when being merged - irrespective of "domains". Does ti work now?

**Comment by AJMHubert** [comment]
Keith said he had a fix, has implemented it, but not merged it back into Felix. If he hasn't got a fix, I do know a commit which does work. I can try to rewind back to that point.

**Pull request merged**
