### PR TITLE
Dm3 read in development

### PR DESCRIPTION
**Pull request by JacobJoseph-gu**
This includes the dm3 reader, the new experimental images folders and workflow, tidied message subroutine and some tidied comments throughout felix.

I have tested this against 79b174d1cd12f1ef42e28aca7aa96101964fdb8d using SrTiO3_short. I ran diff on the final image SrTiO3_+0+0+0.bin and checked that the final refinement variables were the same.

### CODE REVIEW

**Comment by JacobJoseph-gu** [comment]
I have also checked the output doing: Refining Atomic Coordinates, Refining Isotropic Debye Waller Factors, Refining by pairwise maximum gradient for Ca3Mn2O7

**Comment by JacobJoseph-gu** [comment]
Thank you

**Comment by RudoRoemer** [comment]
I was trying to set-up CircleCI, but not sure how to get it to work. Could help with automatic tests.

**Comment by JacobJoseph-gu** [comment]
I was thinking about the usefulness of a test suite. My process is: I have 2 github repositories. I checkout an old commit on one and the new on another. I open a terminal window for each and a script which easily runs felix on each on a corresponding sample. I can then watch the terminal outputs and later run diff on the output files.

**Pull request merged**
