### PR TITLE
fixes #171, updated makefile.includeINT64Nifort

### LINKED ISSUE #171: Error in linking lapack on tinis - Cannot compile
I've tried to compile the master branch of felix on tinis and I'm thrown this error:

```
--- LINKING felix code                                                                                              
/csc/tinis/software/Compiler/GCC/4.9.3/binutils/2.25/bin/ld.gold: error: cannot find -lblas                         
/csc/tinis/software/Compiler/GCC/4.9.3/binutils/2.25/bin/ld.gold: error: cannot find -llapack 
```           

I've used `Module load intel impi imkl FFTW` which works with the old makefile, do we use different modules now?

Cheers,

Alex

### PR DESCRIPTION
**Pull request by JacobJoseph-gu**
changed fortran compiler from mpif90 to mpiifort
and added F90FLAGS for tinis

### CODE REVIEW

**Comment by RudoRoemer** [comment]
I am not sure that using mpiifort instead of mpif90 is correct. Is this what the CSC people want us to do? Where in their documentation does it say so?

**Comment by JacobJoseph-gu** [comment]
It says it on this page:
https://wiki.csc.warwick.ac.uk/twiki/bin/view/Main/ClusterUserGuide

I didn't realise until now that MPIIFORT is a wrapper. Maybe we want a seperate makefile.includeINT for this.

**Comment by RudoRoemer** [comment]
Please test if these settings also compile on the CSC systems (joker and/or aquarius). Thanks.

**Comment by JacobJoseph-gu** [comment]
On both Joker and Aquarius, Felix compiles with `PLATFORM=INT64Nifort` and  `module unload oldmodules; module load newmodules intel impi imkl GCC OpenMPI FFTW`

In these cases, I did not change the INT64Nifort makefile so they all used my updated version with mpiifort alongside slightly different f90 flags.

**Pull request closed without merging**
